{
    'name': 'Insurance Broker Solution',
    'version': '1.0',
    'summary': 'Insurance Broker Solution module for managing Insurance',
    'description': 'Insurance Broker Solution module cover the different aspect of insurance that is managed by the broker',
    'category': 'Insurance',
    'sequence': -100,
    'author': 'Rashid Ali',
    'website': 'https://axiomworld.net/',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'product', 'account', 'fleet', 'stock', 'sale'],
    'data': [
        'data/ir_sequence.xml',
        'data/product_template.xml',
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'views/insurance_policy_view.xml',
        'views/insurance_transaction_view.xml',
        'views/risk_policy_views.xml',
        'views/insurer_partner_view.xml',
        'views/res_partner_ext_view.xml',
        'views/risk_type_view.xml',
        'views/commission_log_view.xml',
        'views/product_ext.xml',
        'views/account_move_ext.xml',
        'views/policy_deduction.xml',
        'views/policy_extension.xml',
        'views/vehicle_year.xml',
        'views/fleet_vehicle_model_year.xml',
        'views/transaction_type.xml',
        'wizard/insurance_policy_wizard.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'insurance_broker_solution/static/src/js/o2m_list_render.js',
            'insurance_broker_solution/static/src/xml/o2m_show_all.xml',
            'insurance_broker_solution/static/src/css/o2m_show_all.css',
        ],
    },
    'installable': True,
    'auto_install': True,
}
